services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h 127.0.0.1 -U $$POSTGRES_USER -d $$POSTGRES_DB",
        ]
      interval: 5s
      timeout: 3s
      retries: 15
    restart: unless-stopped

  brain:
    build: ../services/brain-python
    working_dir: /app
    env_file:
      - ../.env
    environment:
      ALEMBIC_CONFIG: /app/alembic.ini
      DATABASE_URL: ${DATABASE_URL}
      EMBED_DIM: ${EMBED_DIM}
      AUTH_JWT_SECRET: ${AUTH_JWT_SECRET}
      AUTH_JWT_EXPIRES_SECONDS: ${AUTH_JWT_EXPIRES_SECONDS}
      WEB_ORIGIN: ${WEB_ORIGIN}
    volumes:
      - ../services/brain-python/app:/app/app
      - ../services/brain-python/alembic:/app/alembic
      - ../services/brain-python/pyproject.toml:/app/pyproject.toml:ro
      - ../services/brain-python/alembic.ini:/app/alembic.ini:ro
    command: >
      sh -lc 'alembic upgrade head &&
              exec uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload'
    ports: ["8000:8000"]
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/healthz"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

volumes:
  pgdata: {}
